### ISSUE TITLE
Problem with block "turn right x degrees 

### ISSUE THREAD

**Issue by RudolfAtHome** [KitronikLtd/pxt-kitronik-servo-lite#17]
I have a problem with the "**turn right 90 grees**" block: The micro:move makes about **7.5 full revolutions**!
If I want to turn 90 degrees, I have to use the "**turn right 3 degrees**" block. Where does the factor 30 come from?

**Comment by JackAtKitronik** [comment]
Hi, the values needed to turn a :MOVE mini 90 degrees will vary slightly for each :MOVE mini due to manufacturing tolerances in the components.

Check out this blog post to learn how to use the calibrate turn speed block:
[Calibrating 360 Degree Servos For :MOVE mini](https://kitronik.co.uk/blogs/resources/calibrating-360-degree-servos-move-mini?_pos=7&_sid=d13b16cdb&_ss=r)
